/** Canonical site config: use https only, no www. All canonicals and OG URLs derive from SITE_CONFIG.url. */
export const SITE_CONFIG = {
  name: "Bellevue Assurance",
  domain: "bellevueassurance.com",
  url: "https://bellevueassurance.com",
  phone: "1-470-202-8817",
  phoneFormatted: "(470) 202-8817",
  phoneTel: "tel:+14702028817",
  email: "info@bellevueassurance.com",
  npn: "21538890",
  tagline: "Life Insurance Made Simple — Fast Phone Quotes",
};

export const NAV_LINKS = [
  { href: "/quotes", label: "Get Estimate" },
  { href: "/term-life-insurance", label: "Term Life" },
  { href: "/final-expense-insurance", label: "Final Expense" },
  { href: "/burial-insurance", label: "Burial Insurance" },
  { href: "/how-it-works", label: "How It Works" },
  { href: "/states", label: "Coverage Areas" },
  { href: "/guides", label: "Guides" },
  { href: "/blog", label: "Blog" },
  { href: "/about", label: "About" },
  { href: "/faq", label: "FAQ" },
];

export const FOOTER_LINKS = {
  insurance: [
    { href: "/quotes", label: "Free Quote Calculator" },
    { href: "/term-life-insurance", label: "Term Life Insurance" },
    { href: "/final-expense-insurance", label: "Final Expense Insurance" },
    { href: "/burial-insurance", label: "Burial Insurance" },
    { href: "/guaranteed-issue-life-insurance", label: "Guaranteed Issue Life Insurance" },
  ],
  company: [
    { href: "/about", label: "About Us" },
    { href: "/how-it-works", label: "How It Works" },
    { href: "/faq", label: "FAQ" },
    { href: "/contact", label: "Contact" },
    { href: "/guides", label: "Insurance Guides" },
    { href: "/blog", label: "Blog" },
  ],
  legal: [
    { href: "/privacy-policy", label: "Privacy Policy" },
    { href: "/terms", label: "Terms of Service" },
    { href: "/disclosures", label: "Disclosures" },
  ],
};

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
  { value: "DC", label: "District of Columbia" },
];
